//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCoiner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Tokens { get; set; }
        public decimal BTC { get; set; }
        public int Approved { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
